engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
      - reactjs
  fixme:
    enabled: true
ratings:
  paths:
  - "src/*.js"
  - "src/**/*.js"
  - "src/tests/**/*.js"
exclude_paths:
- node_modules/
- public/
- build/
